name: deploy

on:
 push:
  branches:
   - main

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
     with:
      persist-credentials: false
      fetch-depth: 0
   - uses: actions/setup-node@v2-beta
     with:
      node-version: 14
   - run: |
      git config --global user.email "action@github.com"
      git config --global user.name "GitHub Action"
   - run: npm version minor
   - run: |
      git commit -m 'bump version' -a
   - uses: ad-m/github-push-action@master
     with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      branch: ${{ github.ref }}
   - run: npm publish
