name: deploy

on:
 push:
  branches:
   - main

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
     with:
      persist-credentials: false
      fetch-depth: 0
   - uses: actions/setup-node@v2-beta
     with:
      node-version: 14
   - run: |
      git config --global user.email "action@github.com"
      git config --global user.name "GitHub Action"
   - run: npm version minor
   - run: |
      git commit -am 'bump version'
      # do an echo here because git always seems to return a non-zero exit code
      # above due to being a commit ahead of main
      echo
   - uses: ad-m/github-push-action@master
     with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      branch: ${{ github.ref }}
   - run: npm publish
