name: static analysis

on: [ push ]

jobs:
 static-analysis:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2-beta
     with:
      node-version: '14'
   - name: Cache node
     uses: actions/cache@v2
     with:
       path: |
         **/node_modules
       key: ${{ matrix.os }}-${{ hashFiles('**/package-lock.json') }}
       restore-keys: |
        ${{ matrix.os }}-${{matrix.node }}-
        ${{ matrix.os }}-
   - run: npm install
   - run: npm run static-analysis
