name: standard tests

on: [ push ]

jobs:
 test:
  strategy:
   matrix:
    os: [ ubuntu-latest, mac-latest, win-latest ]
    node: [ 12, 14 ]
  runs-on: ${{ matrix.os }}
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2-beta
     with:
      node-version: ${{ matrix.node }}
   - name: Cache node
     uses: actions/cache@v2
     with:
       path: |
         **/node_modules
       key: ${{ matrix.os }}-${{ hashFiles('**/package-lock.json') }}
   - run: npm install
   - run: npm run test
