name: standard tests

on: [ push ]

jobs:
 strategy:
  matrix:
   os: [ ubuntu-latest, mac-latest, win-latest ]
   node: [ 12, 14 ]
 test:
  runs-on: ${{ matrix.os }}
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2-beta
     with:
      node-version: ${{ matrix.node }}
   - run: npm install
   - run: npm run test
